

print("Hello! \n")
print("\tAlbin Rosado Léona")
print("Anayi Yaser")
print("Asplund Marcus ")
print("Bal Emir ")
print("Dahlqvist Chong Leo ")
print("De Moraes Bueno Aweis ")
print("Demissie Andreas ")
print("El Achkar Adrian ")
print("Gacal Yusuf ")
print("Haglund Hugo ")
print("Ismaaciil Abdirahman ")
print("Karlsson Sörstad Dennis ")
print("Ketabchi Arshia ")
print("Khan Samuel ")
print("Kungberg Tim ")
print("Langfoss Bohman Melvin ")
print("Lindeblad Wilma ")
print("Löf Simon ")
print("Mansour Antonio") 
print("Mohamed Abdullahi") 
print("Mounajed Abdel Aziz") 
print("Ngabo David ")
print("Reijer Linus ")
print("Sjunnesson Noah") 
print("Ströberg Benjamin") 
print("Sychowicz Holmqvist Axel") 
print("Tiderman Alexander ")
print("Vukovic Ante ")
print("Zewari Fayaz")

